### ISSUE TITLE
How can I use the same for background-images

### ISSUE THREAD

**Issue by kala725** [shprink/BttrLazyLoading#33]
If I am using background-images , can you please tell, how can I define the different images for different screens. I am able to do it for images.

**Comment by shprink** [comment]
This is not supported sorry.

**Comment by kala725** [comment]
Hi @shprink ,

Is there any reason, why we are not supporting this. I am using this till now with images, but now my requirements are of using background-image..

Till now, I haven't seen the code . Can you please tell, whether the architecture supports the same. If so, I will add a support for the background-images and submit a patch here (will send you a pr for the same)

**Comment by shprink** [comment]
I am sorry but I do not recall why it is not supported. I do not wish to support this project anymore, if you find a way and you want to share with others I will be happy to accept your PR.

THanks
